name: Build and Lint React App

on:
  pull_request:
    branches:
      - main
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      #Checks out the source code repository into the runner's workspace using the `actions/checkout@v2` GitHub Action.
      - name: Checkout Repository
        uses: actions/checkout@v2
      #Sets up Node.js on the runner using the `actions/setup-node@v4` GitHub Action. It specifies that Node.js version 20.x should be used.
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      #Install dependencies, build and lint
      - run: corepack enable
      - run: yarn install
      - run: yarn build
      - run: yarn lint
